//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jela
    {
        public int Id_jela { get; set; }
        public string naziv { get; set; }
        public string slika { get; set; }
        public double cena { get; set; }
        public Nullable<bool> akcija { get; set; }
    }
}
