//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacije
    {
        public int Id_rezervacija { get; set; }
        public string ime { get; set; }
        public string e_mail { get; set; }
        public System.DateTime datum { get; set; }
        public string poruka { get; set; }
        public int IdBrojLjudi { get; set; }
        public int id_termin { get; set; }
    
        public virtual Termini Termini { get; set; }
        public virtual Termini Termini1 { get; set; }
    }
}
