//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termini
    {
        public Termini()
        {
            this.Rezervacijes = new HashSet<Rezervacije>();
            this.Rezervacijes1 = new HashSet<Rezervacije>();
        }
    
        public int Id_termin { get; set; }
        public Nullable<System.TimeSpan> vreme { get; set; }
    
        public virtual ICollection<Rezervacije> Rezervacijes { get; set; }
        public virtual ICollection<Rezervacije> Rezervacijes1 { get; set; }
    }
}
